<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please Sign In_txtemailaddr</name>
   <tag></tag>
   <elementGuidId>cf038270-096a-4ba9-84e8-f1386f1df0f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtemailaddr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtemailaddr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Email Address&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a66a4e9-2c63-40c6-bdb8-0bff6eccea4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtemailaddr</value>
      <webElementGuid>dca33185-6ccd-4cdc-8146-4b0e1dba346d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9247f64a-c6bb-4eae-8b94-c8d50c54bf25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtemailaddr</value>
      <webElementGuid>e0913005-984b-43ee-935e-83fde062bb30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wl-form-control</value>
      <webElementGuid>8499fc89-9fe7-495f-a9fb-cb3596627676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email Address</value>
      <webElementGuid>2581713d-9f90-4897-846d-aad365476bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtemailaddr&quot;)</value>
      <webElementGuid>0b16a336-a979-4960-a37a-7894aadc7a57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtemailaddr']</value>
      <webElementGuid>07c132e1-c72f-4a2f-bb87-7a7fc14b6d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userinfo']/input</value>
      <webElementGuid>83bcabed-fb86-47b6-9060-109e47a2b7a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>2bbd2000-aee9-465b-aa5f-ed9c1b7531eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtemailaddr' and @type = 'text' and @id = 'txtemailaddr' and @placeholder = 'Email Address']</value>
      <webElementGuid>abc02d89-e1f5-4813-b577-93dd1423d222</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
