<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please Sign In_txtpassword</name>
   <tag></tag>
   <elementGuidId>9eec2c02-f68b-478d-9891-7813a88230f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtpassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtpassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Password&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>694689fc-2cac-4971-9687-0a287b08b04b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtpassword</value>
      <webElementGuid>cf6702b9-1956-4532-afde-dfcd7aa74ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>53972d66-aba2-40d4-8236-4e92c5adcab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtpassword</value>
      <webElementGuid>58d36d27-55ff-4b06-af4c-80a978137d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wl-form-control</value>
      <webElementGuid>5b0bc4a1-103c-4c5e-b763-e3cd5a75a18f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>dc4e8d6b-f96c-4dba-89f6-9ab9863e8f4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtpassword&quot;)</value>
      <webElementGuid>bffa06e9-9d68-4aa2-8fda-1bb815a4a64b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtpassword']</value>
      <webElementGuid>ee1cb6d6-bfb0-435c-b8bd-82854355d831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userinfo']/div/input</value>
      <webElementGuid>dd6af0cc-8b2e-4f57-b74c-ff8b9d621070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>c3581a50-9c33-411c-8829-463ff0447b0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtpassword' and @type = 'password' and @id = 'txtpassword' and @placeholder = 'Password']</value>
      <webElementGuid>af600968-115b-46c5-8605-de6a5a774ee4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
