<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_No</name>
   <tag></tag>
   <elementGuidId>f5197f37-6f59-4a2f-b3c8-31f26eabf854</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucMessageBox_btnNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ucMessageBox_btnNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;No &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e6c0aed5-ce83-4d15-9bbf-f83b37255ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>__doPostBack('ctl00$ucMessageBox$btnNo','')</value>
      <webElementGuid>fd98ec3b-2707-4864-a8c4-c37f7bf99bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucMessageBox_btnNo</value>
      <webElementGuid>de8e54a3-c9fd-4c42-b452-6c16bc8630d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5d6a7291-2080-4820-aea2-cf0098525baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wl-btn wl-btn-red wl-marginright10 wl-txt-cntr</value>
      <webElementGuid>3ccb5fb9-9a67-46f1-8e78-68d43f2f5415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    No
                </value>
      <webElementGuid>4a82ba9f-238a-4187-b836-15a2f26a61a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucMessageBox_btnNo&quot;)</value>
      <webElementGuid>c3aeb52d-03f3-4dae-8f21-e7207b6a153e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ucMessageBox_btnNo']</value>
      <webElementGuid>2654e0cd-33da-4548-b31d-dfdd94562ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ucMessageBox_divUcMsgBox']/div/div[3]/div/button[2]</value>
      <webElementGuid>b0505a8d-ca5a-42ed-ad98-e48f3baa6724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/following::button[1]</value>
      <webElementGuid>d42cf687-c247-426b-b172-19df55b70b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Public Holidays'])[2]/following::button[2]</value>
      <webElementGuid>15cd2a01-9bcc-44e2-9ffb-deb9f7cf9d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2024 - Wageloch'])[1]/preceding::button[1]</value>
      <webElementGuid>295022fa-673c-449c-9aa9-c991f5e4648a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>df038d81-84b4-45df-9e15-54f9019bbf40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ucMessageBox_btnNo' and @type = 'button' and (text() = '
                    No
                ' or . = '
                    No
                ')]</value>
      <webElementGuid>7863f6e2-c321-4ff1-9406-b20e3a26baff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
