<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Report</name>
   <tag></tag>
   <elementGuidId>a008016c-e385-4881-abfd-5146868dd341</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.ui-state-default.ui-corner-top.ui-state-hover.ui-state-focus > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='MainContent_tbsReportSelection']/ul/li[9]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Report&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3f5adafa-db69-4834-8170-fa472fe6dc5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#MainContent_tbsReportSelection_tabReport</value>
      <webElementGuid>60db833c-3fe4-4117-aa20-83068178a0f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>25057935-a87b-4b09-87dd-da6523df201f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Report</value>
      <webElementGuid>9a39e567-3aae-4171-96d7-5e88e0fbd36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_tbsReportSelection&quot;)/ul[@class=&quot;ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all&quot;]/li[@class=&quot;ui-state-default ui-corner-top ui-state-hover ui-state-focus&quot;]/a[1]</value>
      <webElementGuid>002f9537-fb8d-402f-a525-28225f231072</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_tbsReportSelection']/ul/li[9]/a</value>
      <webElementGuid>78b89792-d812-433d-bf6b-e3b1540dd547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Report')]</value>
      <webElementGuid>3b656854-e59b-47e9-938c-af4694f1c7ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Range Filters'])[1]/following::a[1]</value>
      <webElementGuid>efaa6f3d-a742-46a0-9f39-7025e753e35a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Staff Filter'])[1]/following::a[2]</value>
      <webElementGuid>8287ecff-037b-4613-b563-30276ba9e3f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Favourites'])[1]/preceding::a[1]</value>
      <webElementGuid>ba4dbb64-ad94-4e6e-9712-e4d72342f509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter By Site Name:'])[1]/preceding::a[2]</value>
      <webElementGuid>d7db31fe-48ad-42d1-8216-ca4c9dc8ad4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#MainContent_tbsReportSelection_tabReport')]</value>
      <webElementGuid>53112aca-ddfb-421e-ac46-85f275c01ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/a</value>
      <webElementGuid>c89af0ed-8ade-4d3d-919c-e2e2923a5272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#MainContent_tbsReportSelection_tabReport' and (text() = 'Report' or . = 'Report')]</value>
      <webElementGuid>e2d813f9-13fd-4b1a-b95d-47d043a2ec7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Report')])[2]</value>
      <webElementGuid>8293c910-1793-4aa2-aae3-91c1565a4bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pre Report'])[1]/following::a[1]</value>
      <webElementGuid>21067cdd-d138-4c33-9769-eabf270aeffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Timesheet Display Preferences'])[1]/following::a[1]</value>
      <webElementGuid>e037f878-3dfa-4325-91cb-465ba30409ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
