<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_OK_fas fa-check wl-btn-icon-left</name>
   <tag></tag>
   <elementGuidId>f1fb44af-f2e8-4cec-bc30-684049b6abd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-check.wl-btn-icon-left</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='aa8fc2b1-4ff0-436e-9f5e-fa901a0741a7']/div/div[3]/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;OK &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b7936bbb-e10d-4bb5-b212-0f314207f915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-check wl-btn-icon-left</value>
      <webElementGuid>13a11c70-a71f-4605-92c0-0b7986d74723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aa8fc2b1-4ff0-436e-9f5e-fa901a0741a7&quot;)/div[@class=&quot;wl-msgbox-modal-content&quot;]/div[@class=&quot;wl-div-margintop10 wl-flex-center&quot;]/button[@class=&quot;wl-btn wl-btn-blue wl-marginright10 wl-flex-right wl-txt-cntr&quot;]/i[@class=&quot;fas fa-check wl-btn-icon-left&quot;]</value>
      <webElementGuid>4663ef57-6779-4df3-9f26-a0a6f3952fdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aa8fc2b1-4ff0-436e-9f5e-fa901a0741a7']/div/div[3]/button/i</value>
      <webElementGuid>2c23e507-d1ea-40df-9e11-2876efeb1b62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/i</value>
      <webElementGuid>6a5d385e-1979-42f7-a2c6-43a1f34d3b14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
