<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_VIEW</name>
   <tag></tag>
   <elementGuidId>3eb329fa-7374-49fa-a2c4-aa4252e5bb05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ctl00_MainContent_grdCurrent']/tbody/tr/td[4]/div/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.wl-txt-blue > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ctl00_MainContent_grdCurrent >> internal:role=link[name=&quot;VIEW &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>50dfdcc1-a6f9-4f9e-9979-eed1bd014319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VIEW</value>
      <webElementGuid>f31b6e4f-2f14-4389-b93b-63bb34ca4e29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_grdCurrent&quot;)/tbody[@class=&quot;ui-widget-content&quot;]/tr[@class=&quot;wijmo-wijgrid-row ui-widget-content wijmo-wijgrid-datarow ui-state-default ui-state-hover&quot;]/td[@class=&quot;wijgridtd wijdata-type-string&quot;]/div[@class=&quot;wijmo-wijgrid-innercell&quot;]/a[@class=&quot;wl-txt-blue&quot;]/span[1]</value>
      <webElementGuid>d172c486-600e-4c23-b102-f179a307d014</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_MainContent_grdCurrent']/tbody/tr/td[4]/div/a/span</value>
      <webElementGuid>273304c1-b49b-4b8c-9b90-c545de0cb960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current Timesheet'])[1]/following::span[1]</value>
      <webElementGuid>262d3b29-2a9c-40ff-8271-944a7ae9f369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[1]/following::span[1]</value>
      <webElementGuid>345da2ad-8e70-4a64-b528-629b8edfdba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Date'])[1]/preceding::span[1]</value>
      <webElementGuid>9833aee6-36c8-4593-874f-b5d2ee32d28e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End Date'])[1]/preceding::span[2]</value>
      <webElementGuid>3d2ab576-006d-4c26-9f2d-3a3786799837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='VIEW']/parent::*</value>
      <webElementGuid>e461c579-1452-4e68-9ff0-bd64a521565f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/span</value>
      <webElementGuid>9ae70a2a-43bf-444c-8122-f00bbc1e9c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'VIEW' or . = 'VIEW')]</value>
      <webElementGuid>6cdfbed5-cdd9-4c55-bd52-7572641f74b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
