<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pre-Submit</name>
   <tag></tag>
   <elementGuidId>e839e4a6-7ad7-440a-8a74-f3e8419811fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='MainContent_ucEditTimesheet_ctl01_btnPreSubmit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MainContent_ucEditTimesheet_ctl01_btnPreSubmit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Pre-Submit &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1c4098ef-1eef-4f1c-bc6c-380991bfd921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>__doPostBack('ctl00$MainContent$ucEditTimesheet$ctl01$btnPreSubmit','')</value>
      <webElementGuid>d8238a26-911a-4fb0-aaea-46989722bfce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MainContent_ucEditTimesheet_ctl01_btnPreSubmit</value>
      <webElementGuid>9a516eff-f878-4a61-bdc6-41127e0ebcae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wl-btn wl-btn-blue wl-width200 wl-txt-cntr wl-flex-right</value>
      <webElementGuid>0957019e-f516-4b53-8355-173504d225e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>362d69d8-7b1c-488a-94df-e0162142b102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Pre-Submit
                        </value>
      <webElementGuid>20c3149f-d9d6-4077-8b29-ffef829abf6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_ucEditTimesheet_ctl01_btnPreSubmit&quot;)</value>
      <webElementGuid>511b41a1-7765-4d1c-b1ed-2aa57ae485b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='MainContent_ucEditTimesheet_ctl01_btnPreSubmit']</value>
      <webElementGuid>20ac5c49-fa81-4ce8-9dab-f2c1cd6ff4bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_ucEditTimesheet_expEditTimesheet']/div[2]/div[3]/div[3]/div[3]/button</value>
      <webElementGuid>146693de-0949-4e9a-a9eb-fabae8ec014e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Calculations'])[1]/following::button[1]</value>
      <webElementGuid>015e6737-da04-4404-b33c-b867332872da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Cost Per Shift'])[1]/following::button[2]</value>
      <webElementGuid>98da9117-9652-409f-861d-1d043bdbf802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2024 - Wageloch'])[1]/preceding::button[1]</value>
      <webElementGuid>dc09bd41-0ef7-4102-b578-44949f6c832e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/button</value>
      <webElementGuid>e4483bd3-4e76-415c-b3e5-bf48268dcd52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'MainContent_ucEditTimesheet_ctl01_btnPreSubmit' and @type = 'button' and (text() = '
                            Pre-Submit
                        ' or . = '
                            Pre-Submit
                        ')]</value>
      <webElementGuid>673a94dd-77e9-4871-bd67-5ca6e49738e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
