<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Hide Empty Columns_MainContent_ucPre_7f9d81</name>
   <tag></tag>
   <elementGuidId>0b14234c-8cba-42a4-9ede-680ee3ef5eab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='MainContent_ucPreSubmit_btnPrint']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MainContent_ucPreSubmit_btnPrint</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2a4d01b1-210f-457a-8311-fb6825ae7e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>__doPostBack('ctl00$MainContent$ucPreSubmit$btnPrint','')</value>
      <webElementGuid>1f5e3f6b-92df-436a-b366-127188b9a27c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MainContent_ucPreSubmit_btnPrint</value>
      <webElementGuid>abaf7d37-6b20-4b9c-a79d-42afb029487d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wl-btn-notext wl-btn-white-noborder</value>
      <webElementGuid>d2db91d5-565a-4bb1-8333-4878b20b73b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b87ea90f-42fd-4751-a646-0f58ac56ce06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_ucPreSubmit_btnPrint&quot;)</value>
      <webElementGuid>fad9b31a-8d50-4ba1-a2db-b699ddece8fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='MainContent_ucPreSubmit_btnPrint']</value>
      <webElementGuid>fc549881-761e-4df0-9f93-05a4de8da468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_ucPreSubmit_pnlPreSubmit']/div[3]/div[2]/div[3]/div/button</value>
      <webElementGuid>7c6eb1c6-c555-4e81-89a3-5dff64f8a045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hide Empty Columns'])[1]/following::button[1]</value>
      <webElementGuid>d28afcf6-5bfc-4c18-9c58-3cd1e1d831a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hide Empty Rows'])[1]/following::button[1]</value>
      <webElementGuid>585ed1da-869f-43d5-a053-095a02473990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Banner, Bruce'])[1]/preceding::button[1]</value>
      <webElementGuid>0aed5d42-610b-4def-8bb2-0c3971c21c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baratheon, Joffrey'])[1]/preceding::button[1]</value>
      <webElementGuid>f4f690ca-420e-4f83-a353-be930b5802b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>8dfed223-983d-4562-93a3-a3112fee68ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'MainContent_ucPreSubmit_btnPrint' and @type = 'button']</value>
      <webElementGuid>5144c7c4-1179-4425-9ca1-361ef0518dcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
