<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SUBMIT</name>
   <tag></tag>
   <elementGuidId>77951045-fea4-4034-a209-a27914df7b7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='MainContent_ucPreSubmit_btnSubmit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MainContent_ucPreSubmit_btnSubmit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;SUBMIT&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b94e97ab-0f0d-4d68-a22e-fdf3457dc4ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>__doPostBack('ctl00$MainContent$ucPreSubmit$btnSubmit','')</value>
      <webElementGuid>9ee17671-10b8-4271-82b0-0723054121b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MainContent_ucPreSubmit_btnSubmit</value>
      <webElementGuid>1de2da11-821f-4a62-ad98-5b2c85bd4d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wl-btn wl-btn-white</value>
      <webElementGuid>55f85ea1-5758-4ccb-9ebf-5ab3adf66674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>82b78e8c-452b-46f8-839c-a69238baf686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SUBMIT</value>
      <webElementGuid>f6526a00-dc95-4a67-92d9-f98c2d9f0d1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_ucPreSubmit_btnSubmit&quot;)</value>
      <webElementGuid>6adc21db-d723-475f-b7ff-d698f100f323</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='MainContent_ucPreSubmit_btnSubmit']</value>
      <webElementGuid>9d54be58-cc17-41f2-bb6d-d14d9d508a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_ucPreSubmit_pnlPreSubmit']/div[3]/div/div/button[4]</value>
      <webElementGuid>0d91f9c0-533f-423f-91f1-1d208f9ecd87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::button[1]</value>
      <webElementGuid>a599abec-8cbb-407b-862e-6d39b0823e3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mark As Already Sent'])[1]/following::button[2]</value>
      <webElementGuid>e439a8c2-d136-4b7d-a1e2-274540b4ef14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adjustments'])[1]/preceding::button[1]</value>
      <webElementGuid>989e6db9-5f95-4ab1-9ee3-8095c4e7ca26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hide Empty Rows'])[1]/preceding::button[2]</value>
      <webElementGuid>527bd1f7-5e78-461c-a612-1bc5b1f8d588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SUBMIT']/parent::*</value>
      <webElementGuid>923aca79-0b6c-4786-8c0b-c1223cfdd8bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>e6d5f261-8d66-4db1-90f1-a06935d8508d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'MainContent_ucPreSubmit_btnSubmit' and @type = 'button' and (text() = 'SUBMIT' or . = 'SUBMIT')]</value>
      <webElementGuid>03c5aa7d-8716-43f3-803e-b12e7e74d294</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
