<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Yes</name>
   <tag></tag>
   <elementGuidId>912b34a4-0900-4b6b-8352-efc08b3e95ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='MainContent_ucMessageBox_btnYes']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MainContent_ucMessageBox_btnYes</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Yes &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>668156b2-8a91-49f2-936d-b19801ce6553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>__doPostBack('ctl00$MainContent$ucMessageBox$btnYes','')</value>
      <webElementGuid>2a4d9e3a-b83c-4804-af13-8839e633d4c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MainContent_ucMessageBox_btnYes</value>
      <webElementGuid>91049df6-0240-4141-863d-f34e0dd147b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>94eb41e2-f719-4730-927e-926174a28db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wl-btn wl-btn-blue wl-marginright10 wl-txt-cntr</value>
      <webElementGuid>f987e38b-1543-4f1e-86f0-714f4292b3eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Yes
                </value>
      <webElementGuid>1ec3a0f0-d0cc-48a3-8245-cf3525bc1b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_ucMessageBox_btnYes&quot;)</value>
      <webElementGuid>73c0e4e1-fd03-48e8-b7a9-1bd282fa0c91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='MainContent_ucMessageBox_btnYes']</value>
      <webElementGuid>2ccf0f30-1e09-41c8-9fbc-226a296f72c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_ucMessageBox_divUcMsgBox']/div/div[3]/div/button</value>
      <webElementGuid>eb822a7e-1de5-4660-a29d-6e9e2c4f2bbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit Timesheet'])[1]/following::button[1]</value>
      <webElementGuid>063582ed-0e97-4f45-a374-2ba90e146a4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Staff Name'])[1]/following::button[1]</value>
      <webElementGuid>aba15dda-80a2-4497-96c7-c9794882f05e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::button[1]</value>
      <webElementGuid>b04dcb33-c451-40ae-ba35-af33c43c83ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/button</value>
      <webElementGuid>9932fedb-a93d-493c-a58e-07ad346f3093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'MainContent_ucMessageBox_btnYes' and @type = 'button' and (text() = '
                    Yes
                ' or . = '
                    Yes
                ')]</value>
      <webElementGuid>f2e21ea0-0d38-400e-9e24-f4de3c9df4e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
