<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Report</name>
   <tag></tag>
   <elementGuidId>ef3cb41c-68d9-4bb6-add3-eca8a00cecbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.ui-state-default.ui-corner-top.ui-state-hover.ui-state-focus > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='MainContent_tbsReportSelection']/ul/li[9]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Report&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c6ab9508-3d42-4ac6-977f-a4157651859a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#MainContent_tbsReportSelection_tabReport</value>
      <webElementGuid>f30dcc3e-b644-4c7e-8682-e26ef7ffc6dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d2f49fd2-c1ab-498c-b970-e4767a8ae9ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Report</value>
      <webElementGuid>8b120f9a-fbde-4046-a5c0-30066fc3a097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_tbsReportSelection&quot;)/ul[@class=&quot;ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all&quot;]/li[@class=&quot;ui-state-default ui-corner-top ui-state-hover ui-state-focus&quot;]/a[1]</value>
      <webElementGuid>67db5bb1-f452-49b4-b053-0d01f82d72c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_tbsReportSelection']/ul/li[9]/a</value>
      <webElementGuid>f0e6c4fd-b1b8-4aa2-bb30-235fe63b61fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Report')]</value>
      <webElementGuid>df684e4f-46cd-4427-97bc-3e829d8c696c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Range Filters'])[1]/following::a[1]</value>
      <webElementGuid>c0474a9c-9962-450a-af06-1e8b048a1455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Staff Filter'])[1]/following::a[2]</value>
      <webElementGuid>bf17e0bf-625a-4516-84f4-e321dce85acb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Favourites'])[1]/preceding::a[1]</value>
      <webElementGuid>96d3cf6d-56c8-453a-9528-2442639c9493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter By Site Name:'])[1]/preceding::a[2]</value>
      <webElementGuid>5f4d608a-d474-4d7f-b4ec-6c554aa9c74d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#MainContent_tbsReportSelection_tabReport')]</value>
      <webElementGuid>bfe7b223-e616-442b-a63f-5bebb5dd0a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/a</value>
      <webElementGuid>54692bf7-0551-4c1a-96a6-2f46b5f21957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#MainContent_tbsReportSelection_tabReport' and (text() = 'Report' or . = 'Report')]</value>
      <webElementGuid>d13e1a84-5acb-4e2e-b6c7-97a4e467a758</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
