<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Favourites_ctl00MainContentctl02tbcRe_c827bc</name>
   <tag></tag>
   <elementGuidId>deae1e96-2249-406c-8137-05da47dce81f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_ctl02_tbcReportsMenu_btnc001d</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_MainContent_ctl02_tbcReportsMenu_btnc001d']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Staff Entitlements (C001d)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1832399f-7d39-46ac-a127-28ebb3857774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6d91b84b-e35a-4951-8d97-db9bb541e0d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$ctl02$tbcReportsMenu$btnc001d</value>
      <webElementGuid>d99b090a-6fdd-4095-9e3d-1f052a056986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Staff Entitlements (C001d)</value>
      <webElementGuid>dcd49587-1266-405d-bd63-05054468a185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>window.open('/Reports/RGStaffList.aspx?ReportId=C001d');return false;</value>
      <webElementGuid>dd93cfc8-8653-476e-9ce8-ba3a143bf7bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_ctl02_tbcReportsMenu_btnc001d</value>
      <webElementGuid>138a89ae-a80e-4f99-a0f6-568a52b3b632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn wl-btn wl-btn-blue reportbutton </value>
      <webElementGuid>c13b6c61-6e35-4f06-a0ed-7eb628edac83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>reportid</name>
      <type>Main</type>
      <value>C001d</value>
      <webElementGuid>329a1245-2a3b-4a02-8d94-6b430f44f6aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>reportpath</name>
      <type>Main</type>
      <value>/Reports/RGStaffList.aspx?ReportId=C001d</value>
      <webElementGuid>7529740e-6d8e-4154-9c28-1ab92207d200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_ctl02_tbcReportsMenu_btnc001d&quot;)</value>
      <webElementGuid>fd30c814-4e2c-47bc-812e-75d3279afe0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_MainContent_ctl02_tbcReportsMenu_btnc001d']</value>
      <webElementGuid>6c89c275-a988-4201-be9e-5bd5279cf37f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_ctl02_tbcReportsMenu_tabHR_REPORTS_pnl']/input[4]</value>
      <webElementGuid>f5a4f046-1bde-481c-b8d0-e6320e349158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input[4]</value>
      <webElementGuid>83d12f63-6552-4ceb-8f59-434b61e50038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$MainContent$ctl02$tbcReportsMenu$btnc001d' and @id = 'ctl00_MainContent_ctl02_tbcReportsMenu_btnc001d']</value>
      <webElementGuid>600206fb-7602-4262-83df-db2dedb7d023</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
