<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Favourites_ctl00MainContentctl02tbcRe_ebf7ce</name>
   <tag></tag>
   <elementGuidId>281a1154-738c-43b2-8406-1bfe0fed7177</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_MainContent_ctl02_tbcReportsMenu_btnr006']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_ctl02_tbcReportsMenu_btnr006</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Pays Hours/Times (R006)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae43be1c-ef41-4086-971d-9cc333ed9800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c8e8de67-7ee3-41e3-81d1-d576187507ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$ctl02$tbcReportsMenu$btnr006</value>
      <webElementGuid>32e5aec7-2210-474f-81bd-fb8427b1b278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Pays Hours/Times (R006)</value>
      <webElementGuid>c01c9f86-abfd-48bc-8503-5c5fbc167847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>window.open('/Reports/RGPaidHours.aspx');return false;</value>
      <webElementGuid>2849ad56-53cb-4270-9f58-e1e0d025e288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_ctl02_tbcReportsMenu_btnr006</value>
      <webElementGuid>3a6963ab-8146-401f-96a6-1d4f33be2f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn wl-btn wl-btn-blue reportbutton </value>
      <webElementGuid>03486bf8-4b5a-4c8c-9a46-f397d9f73c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>reportid</name>
      <type>Main</type>
      <value>R006</value>
      <webElementGuid>fd61c643-f7bc-407a-aede-e3ac9ac55d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>reportpath</name>
      <type>Main</type>
      <value>/Reports/RGPaidHours.aspx</value>
      <webElementGuid>722f44b0-5b0b-40d0-91b6-7eae88e158cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_ctl02_tbcReportsMenu_btnr006&quot;)</value>
      <webElementGuid>fc4406d9-6c02-4e91-b49a-d09533c5829d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_MainContent_ctl02_tbcReportsMenu_btnr006']</value>
      <webElementGuid>70490392-a8a5-48dc-a487-d9450f793132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_ctl02_tbcReportsMenu_tabTIMESHEETS_pnl']/input[6]</value>
      <webElementGuid>c49c4643-650f-4b0f-8415-420c2530ef9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input[6]</value>
      <webElementGuid>b8520e36-8213-44a8-956a-638838b4ca90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$MainContent$ctl02$tbcReportsMenu$btnr006' and @id = 'ctl00_MainContent_ctl02_tbcReportsMenu_btnr006']</value>
      <webElementGuid>f46b380f-70ae-4e93-86c1-99f1fb11d2db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
