<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Favourites_ctl00MainContentctl02tbcRe_d99277</name>
   <tag></tag>
   <elementGuidId>b595f796-58c2-4210-aacd-d892c494b1ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_ctl02_tbcReportsMenu_btnc005</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_MainContent_ctl02_tbcReportsMenu_btnc005']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b3f4c1e-9921-4f44-9abd-72bd056ba220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9d896508-0df5-4b60-a715-cb5e2a98146d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$ctl02$tbcReportsMenu$btnc005</value>
      <webElementGuid>8b81e78d-1053-4f98-b34b-40c201d464c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Staff Turnover Analysis (C005)</value>
      <webElementGuid>cb56e950-2b7d-4038-b805-a612c61b2719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>window.open('/Reports/RGTurnover.aspx');return false;</value>
      <webElementGuid>d428702a-ba19-43ca-8d8a-843e8d7bb3b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_ctl02_tbcReportsMenu_btnc005</value>
      <webElementGuid>5e139f10-908d-4379-8a06-70555bc0eeda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn wl-btn wl-btn-blue reportbutton </value>
      <webElementGuid>96685e40-4dfd-4d92-bfbb-da97f0bda9ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>reportid</name>
      <type>Main</type>
      <value>C005</value>
      <webElementGuid>a30821eb-7a71-4755-ab5a-8b1aceb36848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>reportpath</name>
      <type>Main</type>
      <value>/Reports/RGTurnover.aspx</value>
      <webElementGuid>29080502-b965-442f-96a0-26dfc5776b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_ctl02_tbcReportsMenu_btnc005&quot;)</value>
      <webElementGuid>d73657f1-b90b-42bc-8662-4a4c935ac4ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_MainContent_ctl02_tbcReportsMenu_btnc005']</value>
      <webElementGuid>9c5c2b89-8ec6-4eb0-9265-3c891dc79dcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_ctl02_tbcReportsMenu_tabHR_REPORTS_pnl']/input[10]</value>
      <webElementGuid>46884683-53fb-4402-83c5-70d91e6fb20f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[10]</value>
      <webElementGuid>766dcd27-de37-44e1-acde-cc4c0f46f451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$MainContent$ctl02$tbcReportsMenu$btnc005' and @id = 'ctl00_MainContent_ctl02_tbcReportsMenu_btnc005']</value>
      <webElementGuid>1b67c910-1a7b-45a6-8faa-3a2b1a5c2944</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
