<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Favourites_ctl00MainContentctl02tbcRe_b249c1</name>
   <tag></tag>
   <elementGuidId>bb7dcf69-4fc2-458a-bf0e-ab71ddedc8be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_MainContent_ctl02_tbcReportsMenu_btnc008a']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_ctl02_tbcReportsMenu_btnc008a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Clock times vs Paid times (C008a)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b555944-bb70-4b42-a452-fdd047eb085d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5df3eaab-8714-40e3-a9c2-ce9724837cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$ctl02$tbcReportsMenu$btnc008a</value>
      <webElementGuid>0e11645c-5d2f-4b00-aaa9-a5443cce1390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Clock times vs Paid times (C008a)</value>
      <webElementGuid>ffb3e040-ed3d-4a87-b780-6490aaf19ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>window.open('/Reports/RGExceptions.aspx?ReportId=C008a');return false;</value>
      <webElementGuid>4cb9d227-a7e1-476a-89c4-44842c4db9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_ctl02_tbcReportsMenu_btnc008a</value>
      <webElementGuid>e66a0a18-3b41-4dcd-a7e3-3489c304c6e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn wl-btn wl-btn-blue reportbutton </value>
      <webElementGuid>be99ec90-6a39-433e-85ba-e70f0a9e6f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>reportid</name>
      <type>Main</type>
      <value>C008a</value>
      <webElementGuid>b35167fe-faae-421a-baa2-4b1b71dc0b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>reportpath</name>
      <type>Main</type>
      <value>/Reports/RGExceptions.aspx?ReportId=C008a</value>
      <webElementGuid>733bca79-7962-490b-a722-71dd01f49727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_ctl02_tbcReportsMenu_btnc008a&quot;)</value>
      <webElementGuid>fbcfe26e-047b-444c-a753-108e8501efb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_MainContent_ctl02_tbcReportsMenu_btnc008a']</value>
      <webElementGuid>07710fd2-7409-48ce-a2f1-e34aa1c1383a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_ctl02_tbcReportsMenu_tabCLOCK_TIMES_pnl']/input[3]</value>
      <webElementGuid>8e3a1583-3638-48e5-a907-36391093c6ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input[3]</value>
      <webElementGuid>c1499c4b-d4b3-45e6-8c30-93cc404b6d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$MainContent$ctl02$tbcReportsMenu$btnc008a' and @id = 'ctl00_MainContent_ctl02_tbcReportsMenu_btnc008a']</value>
      <webElementGuid>3e2c897e-06c8-48b6-b743-60313fea8a00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
