<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Favourites_ctl00MainContentctl02tbcRe_017ba2</name>
   <tag></tag>
   <elementGuidId>3f8bf6a6-98a9-4dcf-815d-69953b7b69ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_MainContent_ctl02_tbcReportsMenu_btnr008']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_ctl02_tbcReportsMenu_btnr008</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Roster Budget Report (R008)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fae00f9f-33c0-46b8-8071-2c60219d24fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>dee8700b-9e44-42d1-9eea-ae3bd2197f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$ctl02$tbcReportsMenu$btnr008</value>
      <webElementGuid>aeee2e77-1149-4a89-a12a-b4df420af46e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Roster Budget Report (R008)</value>
      <webElementGuid>5edc057b-0069-4e40-9a6b-a9cfb9094300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>window.open('/Reports/RGRosterBudget.aspx');return false;</value>
      <webElementGuid>1ce9a6aa-2384-4bc5-aad7-4c50007b6e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_ctl02_tbcReportsMenu_btnr008</value>
      <webElementGuid>81c520f1-84f2-4f13-8aac-182a4e8556f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn wl-btn wl-btn-blue reportbutton </value>
      <webElementGuid>7c83c7af-5ed1-456c-bdd0-f107154f143f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>reportid</name>
      <type>Main</type>
      <value>R008</value>
      <webElementGuid>88239e77-90f7-47be-875d-aed65386c6cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>reportpath</name>
      <type>Main</type>
      <value>/Reports/RGRosterBudget.aspx</value>
      <webElementGuid>7d88a247-5d83-48b3-93fd-f10df443a34d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_ctl02_tbcReportsMenu_btnr008&quot;)</value>
      <webElementGuid>658c0c8b-3878-41d9-828f-adc5cb379a97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_MainContent_ctl02_tbcReportsMenu_btnr008']</value>
      <webElementGuid>c9b57721-0028-4491-be53-e58db1a1f64e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_ctl02_tbcReportsMenu_tabROSTERS_pnl']/input[4]</value>
      <webElementGuid>7c040203-edac-4029-9618-e0a133104489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input[4]</value>
      <webElementGuid>89c4c1fc-41a4-4612-8f0a-566798dd3e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$MainContent$ctl02$tbcReportsMenu$btnr008' and @id = 'ctl00_MainContent_ctl02_tbcReportsMenu_btnr008']</value>
      <webElementGuid>f719cf77-8325-4778-85e6-2d5585406e56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
