<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Done</name>
   <tag></tag>
   <elementGuidId>1f14fbf5-0cca-4d14-95cb-64d9199294fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MainContent_ucEditClockTimes_btnEditStaffClockTimeDone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='MainContent_ucEditClockTimes_btnEditStaffClockTimeDone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Done &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e1c68ca4-bec9-4489-8750-8295e2624c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>__doPostBack('ctl00$MainContent$ucEditClockTimes$btnEditStaffClockTimeDone','')</value>
      <webElementGuid>ab9a274a-03a6-4b31-9aeb-6d350b06cadb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MainContent_ucEditClockTimes_btnEditStaffClockTimeDone</value>
      <webElementGuid>d231b10e-f070-4034-a291-799a2e593804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wl-btn wl-btn-blue</value>
      <webElementGuid>59aab3f5-65a6-4958-844b-150121b177d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6d8d44eb-371b-427a-a7a4-1d4e887c5651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Done
                    </value>
      <webElementGuid>f39cc9e2-1aea-477b-bb1b-6ce6631d471d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_ucEditClockTimes_btnEditStaffClockTimeDone&quot;)</value>
      <webElementGuid>dc29f20a-ea90-4869-a3c9-23b3e7a1fe7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='MainContent_ucEditClockTimes_btnEditStaffClockTimeDone']</value>
      <webElementGuid>77f1a9ef-e2f9-4357-8c5c-bb5709980c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_ucEditClockTimes_pnlEditStaffClockTime']/div[4]/button[2]</value>
      <webElementGuid>914079b2-c422-4e9f-b617-30e4a6d7beed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>6751b579-1ced-460d-96f7-a3e91a6b2b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time:'])[1]/following::button[2]</value>
      <webElementGuid>e259e2c7-b53f-4001-a43d-53e400b5ae22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2024 - Wageloch'])[1]/preceding::button[1]</value>
      <webElementGuid>79577a20-89b8-44f1-acc5-fbc5b33aa6c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button[2]</value>
      <webElementGuid>ee60ea2d-d9cf-4385-abde-ff3ae7636e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'MainContent_ucEditClockTimes_btnEditStaffClockTimeDone' and @type = 'button' and (text() = '
                        Done
                    ' or . = '
                        Done
                    ')]</value>
      <webElementGuid>0e9dc13e-0db1-4e39-a198-4968ba89c060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='MainContent_ucEditClockTimes_btnStaffClockTimeDone']</value>
      <webElementGuid>43593218-0694-4236-8a9e-1d8e4953f073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_ucEditClockTimes_pnlStaffClockTime']/div[3]/button[2]</value>
      <webElementGuid>f7bcb70b-5f25-4461-be31-3f8a4880041d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create'])[1]/following::button[1]</value>
      <webElementGuid>07e59250-6056-42c4-8f35-b0ad6b77ddd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location'])[1]/following::button[2]</value>
      <webElementGuid>8099bf10-e196-46ea-829e-d42ec539bfbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button[2]</value>
      <webElementGuid>ded45559-50ca-44c8-87e7-d50ff79c1027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'MainContent_ucEditClockTimes_btnStaffClockTimeDone' and @type = 'button' and (text() = '
                        Done
                    ' or . = '
                        Done
                    ')]</value>
      <webElementGuid>3eb6832b-18c8-4e26-81ad-0032b73f7ffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='MainContent_ucEditClockTimes_btnDone']</value>
      <webElementGuid>a9d95436-ce1b-4bd0-a5e9-759432e8c973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_ucEditClockTimes_pnlClockTimes']/div[3]/button[2]</value>
      <webElementGuid>7a8e5b0c-1bca-400e-a21f-08a2de918ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In'])[1]/following::button[2]</value>
      <webElementGuid>db49d632-92cc-4c30-91fc-0abf5996746e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'MainContent_ucEditClockTimes_btnDone' and @type = 'button' and (text() = '
                        Done
                    ' or . = '
                        Done
                    ')]</value>
      <webElementGuid>71b949ca-a084-4991-b646-0f71f32edb7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
