<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Create</name>
   <tag></tag>
   <elementGuidId>2cd72f30-e8c4-4955-9db0-0d3449c8cc39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MainContent_ucEditClockTimes_btnStaffClockTimeCreate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='MainContent_ucEditClockTimes_btnStaffClockTimeCreate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>db02a184-2b02-43ac-b876-8a0c97cc7889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>__doPostBack('ctl00$MainContent$ucEditClockTimes$btnStaffClockTimeCreate','')</value>
      <webElementGuid>eea5ffce-1538-44ef-9846-beba28658ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MainContent_ucEditClockTimes_btnStaffClockTimeCreate</value>
      <webElementGuid>806bd658-06ba-4da2-af9b-944a912171b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wl-btn wl-btn-green</value>
      <webElementGuid>5cd35fcb-362e-4398-a370-7f94ee19ca40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bbe240b2-1662-4108-aa17-6fc2e3527a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Create
                    </value>
      <webElementGuid>488d6789-1efc-4f40-a378-000ea28ff0c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_ucEditClockTimes_btnStaffClockTimeCreate&quot;)</value>
      <webElementGuid>08fc27ce-3cce-4c01-af8a-2f8dfc0a2a07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='MainContent_ucEditClockTimes_btnStaffClockTimeCreate']</value>
      <webElementGuid>c1db8394-814f-477c-a8e2-d8e5e5f3866f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_ucEditClockTimes_pnlStaffClockTime']/div[3]/button</value>
      <webElementGuid>2077621e-538f-43c5-9e12-d8b63449089e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location'])[1]/following::button[1]</value>
      <webElementGuid>83908b03-2c37-4488-983f-6019b16c1271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time'])[1]/following::button[1]</value>
      <webElementGuid>a6f11b01-05fc-4ce7-b2b4-4d7a30c6a830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done'])[1]/preceding::button[1]</value>
      <webElementGuid>15730f4b-c97c-4de6-aafa-1c15382f3aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>3da5eece-5f6a-4960-be4c-2dca9bd46dd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'MainContent_ucEditClockTimes_btnStaffClockTimeCreate' and @type = 'button' and (text() = '
                        Create
                    ' or . = '
                        Create
                    ')]</value>
      <webElementGuid>00ec8604-74fd-4b0d-b72e-6449d68ea772</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
