<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>c85d9ae0-dff8-4ed6-bb39-8c2396a9488b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_MainContent_ucEditClockTimes_grdStaffClockTime_div']/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.wijmo-wijsuperpanel-contentwrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.wijmo-wijsuperpanel-contentwrapper</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>08e04fe8-b403-46f8-973b-1ef38ff8b4b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wijmo-wijsuperpanel-contentwrapper</value>
      <webElementGuid>e36b6dac-7402-4732-8a68-89ca20ca7761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>    </value>
      <webElementGuid>e78e78c5-e87b-473f-96f8-d88689c831a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_ucEditClockTimes_grdStaffClockTime_div&quot;)/div[@class=&quot;ui-widget wijmo-wijgrid  wijgridouterdiv ui-widget-content ui-corner-all&quot;]/div[@class=&quot;wijmo-wijgrid-fixedview&quot;]/div[@class=&quot;wijmo-wijgrid-scroller  wijmo-wijsuperpanel ui-widget ui-widget-content ui-corner-all&quot;]/div[@class=&quot;wijmo-wijsuperpanel-statecontainer&quot;]/div[@class=&quot;wijmo-wijsuperpanel-contentwrapper&quot;]</value>
      <webElementGuid>aca11a54-e469-477a-8dee-68381b427f1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_MainContent_ucEditClockTimes_grdStaffClockTime_div']/div/div/div/div/div</value>
      <webElementGuid>18262b62-a84d-4335-8dc4-dbb489a2e7fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Staff Member:'])[1]/following::div[7]</value>
      <webElementGuid>07685614-e638-444c-9331-f5e196a25630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clock Time'])[1]/following::div[11]</value>
      <webElementGuid>43321545-191e-455c-9aee-1fe5644e7c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type'])[1]/preceding::div[9]</value>
      <webElementGuid>4e7784c4-8a60-4c17-8492-121b18dd56c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time'])[1]/preceding::div[10]</value>
      <webElementGuid>0c309989-a886-4f58-ae13-d6d95bf0a139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/div/div</value>
      <webElementGuid>a472b7cf-9635-430f-90d5-53857c8814aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '    ' or . = '    ')]</value>
      <webElementGuid>9ec3aec2-6615-496e-ad7a-02938729c6f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
