<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Done_fas fa-check wl-btn-icon-left_1</name>
   <tag></tag>
   <elementGuidId>02d09cf6-6c9e-4492-87f6-14b0f3858aed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='MainContent_ucEditClockTimes_btnStaffClockTimeDone']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-check.wl-btn-icon-left</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Done &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>aaa60495-7107-4beb-86a1-ec94b94578fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-check wl-btn-icon-left</value>
      <webElementGuid>1f3c0384-3ed4-4f6d-a630-ad4036cc1207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_ucEditClockTimes_btnStaffClockTimeDone&quot;)/i[@class=&quot;fas fa-check wl-btn-icon-left&quot;]</value>
      <webElementGuid>3aae7309-b1f4-436d-864d-1fec2afa5501</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='MainContent_ucEditClockTimes_btnStaffClockTimeDone']/i</value>
      <webElementGuid>47585a8f-a484-4a03-b753-b4c9ef79cc60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button[2]/i</value>
      <webElementGuid>af8351af-4f1f-49d1-8367-22d38acabf35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
