<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Whos Here</name>
   <tag></tag>
   <elementGuidId>5396a055-9766-465a-bd0d-2b27d5e74510</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MainContent_btnPrintWhosHere > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='MainContent_btnPrintWhosHere']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8dc444f6-203b-43ed-9250-c884f490a861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Who's Here</value>
      <webElementGuid>864c77be-d882-4145-b737-13c5ccb5168d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_btnPrintWhosHere&quot;)/span[1]</value>
      <webElementGuid>839cb2c9-6d61-4b47-af48-46e2c5ff8a14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='MainContent_btnPrintWhosHere']/span</value>
      <webElementGuid>a25288cd-c02c-4f30-a2dd-5792b83ab1c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cook'])[2]/following::span[1]</value>
      <webElementGuid>8c70d55b-53b9-4c52-91a1-7d0e2833f164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Training'])[2]/following::span[1]</value>
      <webElementGuid>e33ebdb0-9073-4a8d-b025-eb2bca398d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clock On'])[1]/preceding::span[1]</value>
      <webElementGuid>b3fc8836-af0e-47ad-bae2-d130ae367ffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clock Off'])[1]/preceding::span[2]</value>
      <webElementGuid>226241d3-46f1-44b0-9ed8-69a5a2897e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/span</value>
      <webElementGuid>e71dd415-8709-4f09-b3cc-9f9b4a82fe8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = concat(&quot;Who&quot; , &quot;'&quot; , &quot;s Here&quot;) or . = concat(&quot;Who&quot; , &quot;'&quot; , &quot;s Here&quot;))]</value>
      <webElementGuid>9233895d-6f85-4163-893d-800c49eee635</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
