<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Banner</name>
   <tag></tag>
   <elementGuidId>e2b795c6-c32a-44a7-8257-dc644edaeef9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.wijmo-wijgrid-innercell > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ctl00_MainContent_ctl01_grdStaffList']/tbody/tr/td[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>283a4121-dc7f-4cd6-86c9-9c1a84a438f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$MainContent$ctl01$grdStaffList$ctl03$ctl00','')</value>
      <webElementGuid>ae8fc822-2dc1-4ca7-9452-9ba10b2c9175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Banner</value>
      <webElementGuid>9b04759e-00ff-481b-95d7-780a0f5de7f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_ctl01_grdStaffList&quot;)/tbody[@class=&quot;ui-widget-content&quot;]/tr[@class=&quot;wijmo-wijgrid-row ui-widget-content wijmo-wijgrid-datarow ui-state-default ui-state-hover&quot;]/td[@class=&quot;wijgridtd wijdata-type-string&quot;]/div[@class=&quot;wijmo-wijgrid-innercell&quot;]/a[1]</value>
      <webElementGuid>4559d5d5-88bb-46a8-9ae1-609405fa3420</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_MainContent_ctl01_grdStaffList']/tbody/tr/td[2]/div/a</value>
      <webElementGuid>e1671839-04e5-42be-a725-1d0165798a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Banner')]</value>
      <webElementGuid>8557599c-d665-42f9-b7a7-ec1bfa6e0247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hide Base Rate'])[1]/following::a[1]</value>
      <webElementGuid>25239102-bfd0-4e43-a599-15e3c15943c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Terminated Staff'])[1]/following::a[1]</value>
      <webElementGuid>b8f928a4-e7fc-4356-adea-624f55db310d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bruce'])[1]/preceding::a[1]</value>
      <webElementGuid>ecb3479a-b4c9-44a2-b19f-bad29d3d6920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RSP, Kitchenhand, Chef, Maintenance'])[1]/preceding::a[2]</value>
      <webElementGuid>2ff0c1c7-5ce8-4632-8c47-83d0e5a330d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Banner']/parent::*</value>
      <webElementGuid>b860773c-b1bf-48a5-a024-7ba866e7e87f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$MainContent$ctl01$grdStaffList$ctl03$ctl00','')&quot;)]</value>
      <webElementGuid>8d3cb351-5bd9-41a8-bf96-95437f30947e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/a</value>
      <webElementGuid>f8cabbb6-7a06-4891-878e-e966334cf596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$MainContent$ctl01$grdStaffList$ctl03$ctl00&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Banner' or . = 'Banner')]</value>
      <webElementGuid>d2aad4bd-f144-4efe-9872-3c56274c46e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
