<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Options</name>
   <tag></tag>
   <elementGuidId>44ee1457-f59d-4959-a428-f2ce402291c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.ui-state-default.ui-corner-top.ui-state-hover.ui-state-focus > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='MainContent_ucStaffEdit2_tbsStaffedit']/ul/li[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>add4b384-e7ac-4b3d-9353-678d20376333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#MainContent_ucStaffEdit2_tbsStaffedit_tpOptions</value>
      <webElementGuid>3da58e9a-5299-437d-a21a-0e7c664c4d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>31be02fd-f1d3-40da-9dd8-b90fa8f15221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Options</value>
      <webElementGuid>2ad800b3-a0f5-4564-986e-6db197368cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_ucStaffEdit2_tbsStaffedit&quot;)/ul[@class=&quot;ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all&quot;]/li[@class=&quot;ui-state-default ui-corner-top ui-state-hover ui-state-focus&quot;]/a[1]</value>
      <webElementGuid>438f0535-2d9d-44ad-824c-decd70c6112b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_ucStaffEdit2_tbsStaffedit']/ul/li[6]/a</value>
      <webElementGuid>9324fac8-a7f9-4d66-ada6-42884367b58c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Options')]</value>
      <webElementGuid>7ffa8f2e-c2f2-4fa9-95c2-863ff0e33e5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rates'])[1]/following::a[1]</value>
      <webElementGuid>f4994365-69e1-4bbe-bb7d-a812aa5349a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Central Control'])[1]/following::a[2]</value>
      <webElementGuid>367d0b97-025a-469f-87df-27763ca659a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qualifications'])[2]/preceding::a[1]</value>
      <webElementGuid>540d6a98-ba74-4c31-9be5-340104a781ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accruals'])[1]/preceding::a[2]</value>
      <webElementGuid>dc618a61-be5b-4d12-b80a-b2a17ea50260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Options']/parent::*</value>
      <webElementGuid>5cbf00d5-8368-4915-abe8-e8b1acdfa76f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#MainContent_ucStaffEdit2_tbsStaffedit_tpOptions')]</value>
      <webElementGuid>507cf9de-9a6a-4794-b57d-7e469ff5c200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[6]/a</value>
      <webElementGuid>4bcc0db5-2836-467f-a47c-700b240159d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#MainContent_ucStaffEdit2_tbsStaffedit_tpOptions' and (text() = 'Options' or . = 'Options')]</value>
      <webElementGuid>49b79fc4-0b26-4a0d-8e18-9db1d93ab97f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
