<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Payroll</name>
   <tag></tag>
   <elementGuidId>316f28bc-80aa-4780-ad57-d51f8e0f1727</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.ui-state-default.ui-corner-top.ui-state-hover.ui-state-focus > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='MainContent_ucStaffEdit2_tbsStaffedit']/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5bff76e5-bf80-4b62-a49a-d6a5b291a29e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#MainContent_ucStaffEdit2_tbsStaffedit_tpPayroll</value>
      <webElementGuid>20267107-8cec-4978-b596-d4f70095daa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>1aa2bf3f-8ab9-4d83-942b-80f274e55b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Payroll</value>
      <webElementGuid>08e6714d-89ba-4b9d-b66b-18d3dd597a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_ucStaffEdit2_tbsStaffedit&quot;)/ul[@class=&quot;ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all&quot;]/li[@class=&quot;ui-state-default ui-corner-top ui-state-hover ui-state-focus&quot;]/a[1]</value>
      <webElementGuid>d21a5e88-c314-46bf-a304-2c520be4129b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_ucStaffEdit2_tbsStaffedit']/ul/li[2]/a</value>
      <webElementGuid>af9c6507-f7a8-4212-815f-a7dcb3dcb14d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Payroll')])[5]</value>
      <webElementGuid>d133dc8d-625c-4956-8d5f-1d97860bf053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rostering'])[1]/following::a[1]</value>
      <webElementGuid>1b3261eb-7f0f-4282-b398-87127bc870fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of Birth'])[1]/following::a[2]</value>
      <webElementGuid>3c7a31c0-bd92-4b5c-a1c0-0a4df2d0b373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stores'])[1]/preceding::a[1]</value>
      <webElementGuid>4b8c82cf-12f7-407e-a43d-9e934d02d0db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Central Control'])[1]/preceding::a[2]</value>
      <webElementGuid>22045d9a-6ffd-41ff-952d-49a4f4d6ec2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#MainContent_ucStaffEdit2_tbsStaffedit_tpPayroll')]</value>
      <webElementGuid>006c0e74-81c7-4391-8904-e81c3c09bcef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[2]/a</value>
      <webElementGuid>731adac6-7c99-4b0a-8d03-24bec0a72587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#MainContent_ucStaffEdit2_tbsStaffedit_tpPayroll' and (text() = 'Payroll' or . = 'Payroll')]</value>
      <webElementGuid>6727ad3a-618b-4baf-8ddf-8621408372db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
