<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pay level_pnlOther</name>
   <tag></tag>
   <elementGuidId>8d9e8823-41dd-4967-abe4-d379b45d6af1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pnlOther</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pnlOther']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8f5efd5b-94f8-404e-8749-6f94516ae163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pnlOther</value>
      <webElementGuid>ff5bda0b-59f8-45dd-af84-86958ccb1d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pnl_pg_group</value>
      <webElementGuid>d3fad586-4df4-456f-a963-43a23cc3f57b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pnlOther&quot;)</value>
      <webElementGuid>c6cc3d7e-c11f-41b5-9d9a-b1fb62cdd6ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='pnlOther']</value>
      <webElementGuid>70b703f3-9638-4892-82ee-66b916dd0a28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_ucStaffEdit2_tbsStaffedit_pnltpPayRoll']/div[2]</value>
      <webElementGuid>e1ad262f-c31f-4817-8009-fd2b6b2cd33e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay level'])[1]/following::div[2]</value>
      <webElementGuid>0d54b03b-8e37-4257-9150-e25eeb8ba921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay group'])[1]/following::div[4]</value>
      <webElementGuid>09bb4a6d-d668-4a7a-8d1b-388b8aea2d65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rates'])[2]/preceding::div[4]</value>
      <webElementGuid>536e22b2-7834-44f9-9422-1926dbc57c0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Base Hourly'])[1]/preceding::div[21]</value>
      <webElementGuid>d958bcbc-9e77-4581-95b3-840e24edad15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div[2]/div/div[2]</value>
      <webElementGuid>30a34234-0c2b-401d-9878-5749584bd612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'pnlOther']</value>
      <webElementGuid>65981fc4-8728-4e4e-8e16-e3792ee146ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
