<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Payroll Code_ctl00MainContentucStaffE_582538</name>
   <tag></tag>
   <elementGuidId>6753e265-5fb7-41ae-85c6-e3a34337a3c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtPayrollCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtPayrollCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtPayrollCode</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3de105c6-414b-48e0-b27f-170c389a9e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$ucStaffEdit2$txtPayrollCode</value>
      <webElementGuid>0baefe46-0f71-425a-b447-87d1694b2d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f7f9eb92-e68b-4cde-aadd-4cb2d57377be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtPayrollCode</value>
      <webElementGuid>0fee926a-1d00-428f-a363-1b95380804f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wl-form-control</value>
      <webElementGuid>c16efeb9-6c0b-41ea-808b-52e8a7394421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtPayrollCode&quot;)</value>
      <webElementGuid>7e7da96b-03c6-4193-96d5-55ef7f849823</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtPayrollCode']</value>
      <webElementGuid>a8be3a3d-e400-484d-85ff-92c85e7159b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_ucStaffEdit2_pnlPayrollCode']/input</value>
      <webElementGuid>66cafb89-e94b-4bfd-b67c-e170fd1b7965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>4d4134be-6c3b-4e62-b625-e0e087c59669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$MainContent$ucStaffEdit2$txtPayrollCode' and @type = 'text' and @id = 'txtPayrollCode']</value>
      <webElementGuid>337e82be-364c-4eb9-bfaa-4a0d84458696</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
