<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Surname_ctl00MainContentucStaffEdit2t_8ee10f</name>
   <tag></tag>
   <elementGuidId>a3d26775-87d6-4f04-9aae-80d20a3d9c50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtSurname']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtSurname</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtSurname</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68dfcbb7-a5d5-4a9b-ba15-51cae318ad76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$ucStaffEdit2$txtSurname</value>
      <webElementGuid>35a2ad41-a0fa-499e-a9c7-b7825d59b1c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cf9daa50-8bf7-43c5-b7ad-a79d834aa2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtSurname</value>
      <webElementGuid>2be8629f-80a6-4295-bc5e-7b825a38cb4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wl-form-control fll</value>
      <webElementGuid>dc4afae0-0fa5-4d53-bd52-02c45f0ac933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtSurname&quot;)</value>
      <webElementGuid>213e17c5-7e1e-4871-bef3-8993bfff09f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtSurname']</value>
      <webElementGuid>7d0e8910-93c1-4644-a7e7-19691c25460c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_ucStaffEdit2_pnlSurname']/input</value>
      <webElementGuid>96baa221-ffce-43b3-bd58-3c12a7978973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[3]/input</value>
      <webElementGuid>ca455286-acc0-46d8-a611-aaa8d2e5adb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$MainContent$ucStaffEdit2$txtSurname' and @type = 'text' and @id = 'txtSurname']</value>
      <webElementGuid>9577098b-0c27-4327-bc45-11d6e59c19d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
