<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_ctl00MainContentucStaffEdi_403476</name>
   <tag></tag>
   <elementGuidId>2afbffbd-884b-4086-97e0-2be66dd65d7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtFirstname']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtFirstname</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtFirstname</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>99436884-b404-4cca-b844-f5497e01dbdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$ucStaffEdit2$txtFirstname</value>
      <webElementGuid>8b451c7f-5a9b-41c0-b3fc-360e15fb233c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>52cc2712-6f35-45b6-b5e8-38a72a334e29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtFirstname</value>
      <webElementGuid>3b1d6d4f-5340-4f28-b0e6-3e8a0d738a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wl-form-control fll</value>
      <webElementGuid>ac93f2ce-22a5-4e83-be50-67ef451b6991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtFirstname&quot;)</value>
      <webElementGuid>b86bdfc3-699e-4822-838a-89f11ea28222</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtFirstname']</value>
      <webElementGuid>fc5c15d8-a902-48ee-827c-0245c00dba7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_ucStaffEdit2_pnlFirstname']/input</value>
      <webElementGuid>23932940-f4be-4517-aa86-1f0e0a88f770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>87f70895-53d1-4d9a-9b04-b4f995a2280c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$MainContent$ucStaffEdit2$txtFirstname' and @type = 'text' and @id = 'txtFirstname']</value>
      <webElementGuid>e68427e1-714a-4136-bab2-cf20d96c999c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
