<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_ctl00MainContentucStaffEdit2txtEmail</name>
   <tag></tag>
   <elementGuidId>f4280e89-60c8-4b73-bce8-ffcb6da85f2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtEmail</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>61456252-84f0-4b76-8036-207647b06f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$ucStaffEdit2$txtEmail</value>
      <webElementGuid>244b5065-8bd6-4a6f-9858-229d2b084bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>5fc7b0a0-9029-44c0-a122-033ce1c57b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtEmail</value>
      <webElementGuid>6cc52885-42ee-4113-a29f-39d56f6b3f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wl-form-control</value>
      <webElementGuid>e9f7df0c-d759-46c2-aefc-821e6c752cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtEmail&quot;)</value>
      <webElementGuid>f30d36c5-3209-4cf4-88f8-049a33985a5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtEmail']</value>
      <webElementGuid>9f793718-e126-4ff5-b8eb-75af5ada12b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_ucStaffEdit2_pnlEmail']/input</value>
      <webElementGuid>305b4bf5-602a-45e1-8d6c-116756d95eb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[2]/input</value>
      <webElementGuid>c899eafc-85b3-42aa-9183-1898339f289b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$MainContent$ucStaffEdit2$txtEmail' and @type = 'email' and @id = 'txtEmail']</value>
      <webElementGuid>e8ce07a3-a3c9-4cf0-90df-442e058f7ab9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
