<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Rosters</name>
   <tag></tag>
   <elementGuidId>75f4653d-7377-49dc-938f-4566a8576b6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='aRosters']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#aRosters</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Rosters&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>24549ee1-338b-4a88-884e-c91a58249ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aRosters</value>
      <webElementGuid>9d0e9ac9-97a4-47fa-ab79-c36df3f256dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>goto</name>
      <type>Main</type>
      <value>Rosters</value>
      <webElementGuid>b9cd45af-4797-40ca-9673-770d88f8c90c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Rosters</value>
      <webElementGuid>c34c3320-8829-4394-8b05-8df75cfac867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$aRosters&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))</value>
      <webElementGuid>17ee6f10-524b-4456-9d1a-6da450ecaf70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wl-mainmenu-selected</value>
      <webElementGuid>9488917b-c1e7-4b20-80b7-250c8dfaf29f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rosters</value>
      <webElementGuid>7f6b00e6-d075-4c4b-a12d-2a06118e62e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aRosters&quot;)</value>
      <webElementGuid>8b4e8912-86f0-48a9-9197-bb9409ac4e54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='aRosters']</value>
      <webElementGuid>f62b2c0f-f186-4dc8-89ec-e89ed8775225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='mnuRosters']/a</value>
      <webElementGuid>a52d749b-c96d-45b9-ac36-15d4c2b69a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Rosters')]</value>
      <webElementGuid>26ffec4e-2b94-42f4-9254-0eb79869bc7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::a[1]</value>
      <webElementGuid>8fc6a68e-81c2-499e-a01e-27e367e49759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Timesheets'])[1]/preceding::a[1]</value>
      <webElementGuid>850ad2c8-f166-48ab-ab39-ee0b850f0d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Staff'])[1]/preceding::a[2]</value>
      <webElementGuid>fa5df5de-3520-4b86-8e24-979e7031fbc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rosters']/parent::*</value>
      <webElementGuid>95d77978-2c66-4fb0-9317-7cccc633cafc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$aRosters&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))')]</value>
      <webElementGuid>d7659356-f1e3-4e23-a71a-80bbc912e525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>2e32617e-2959-4dad-89f4-92cfb11dbc48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'aRosters' and @title = 'Rosters' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$aRosters&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))' and (text() = 'Rosters' or . = 'Rosters')]</value>
      <webElementGuid>07e59fa4-7efe-4d41-bb85-2709d7d310e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
