<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>2b67c347-333c-4a76-a483-f776a0bc6176</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='MainContent_ucEditRoster_ctl01_btnSave']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MainContent_ucEditRoster_ctl01_btnSave</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Save &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>006a36ff-293d-49e2-85b1-d2545180b84f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if (typeof(Page_ClientValidate) == 'function') Page_ClientValidate(''); __doPostBack('ctl00$MainContent$ucEditRoster$ctl01$btnSave','')</value>
      <webElementGuid>c67d4597-f3fa-4a1b-abd2-f79d9f687360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MainContent_ucEditRoster_ctl01_btnSave</value>
      <webElementGuid>8b32ebcd-b008-4254-9d20-ed52952ae3c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wl-btn wl-btn-white wl-marginright10 wl-control-editroster</value>
      <webElementGuid>4882597d-5921-4746-b376-7f57cf43c4cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>14eaf99b-f528-4c5d-b4a3-5a32b4bd932f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Save
                    </value>
      <webElementGuid>51b7a4e3-58ff-40bf-a5d1-8a6c3df17630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_ucEditRoster_ctl01_btnSave&quot;)</value>
      <webElementGuid>769d6673-9f49-49e7-a679-c7db9b36a3f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='MainContent_ucEditRoster_ctl01_btnSave']</value>
      <webElementGuid>d3d792b5-1292-44ab-94cc-2a2af999f80d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainContent_ucEditRoster_expEditRoster']/div[2]/div/div/div/button[2]</value>
      <webElementGuid>d271c5df-bb20-4d10-a3f6-a2850e7b9911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DELETE ROSTER'])[1]/following::button[1]</value>
      <webElementGuid>abb534af-e571-4156-a28f-c4013a93f8db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Cost for Monday'])[1]/following::button[2]</value>
      <webElementGuid>2ddd4594-2c1e-4951-92a0-55fd27d3c4e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RePublish'])[1]/preceding::button[1]</value>
      <webElementGuid>e1d0e722-de23-4a7d-8007-55ba01c6e5cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>92d4f4c4-61ea-4bfc-8ccd-7e1d14c11419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'MainContent_ucEditRoster_ctl01_btnSave' and @type = 'button' and (text() = '
                        Save
                    ' or . = '
                        Save
                    ')]</value>
      <webElementGuid>1c8accf8-6c90-4eb7-969b-bc2ac479eb7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
