<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_BT_RosterStrip_Canvas_0</name>
   <tag></tag>
   <elementGuidId>5723914f-ab0a-4b18-bcf3-a12e78e0ce4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='RosterStrip_Canvas_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#RosterStrip_Canvas_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#RosterStrip_Canvas_0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>bd004e8d-c251-4168-ad4c-c518c4767cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>666</value>
      <webElementGuid>3dae18c1-fcba-4ae2-b2a5-74ca754ce8a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>e302793b-f5c0-44ef-8bad-2014189df198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wl-canvas-rosterstrip</value>
      <webElementGuid>1fc997d4-7e67-4ebf-88de-314a13c105a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RosterStrip_Canvas_0</value>
      <webElementGuid>783d7107-aff0-4f2c-b0ec-d1cf25c6bb7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RosterStrip_Canvas_0&quot;)</value>
      <webElementGuid>0b2d4412-c5fc-4b58-8d4f-58d1db2c8426</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='RosterStrip_Canvas_0']</value>
      <webElementGuid>464f722a-479e-499f-b5f4-a345dd396766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RosterStrip_0']/canvas</value>
      <webElementGuid>d1ab6883-099d-4057-95bc-06fc30cf185b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>35b3ec5c-41a1-4dc6-a379-286485dc2fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'RosterStrip_Canvas_0']</value>
      <webElementGuid>4f7fe18d-2ee3-4119-a9e9-8c44fffc73fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
