<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Done_fas fa-user-plus wl-btn-icon-left</name>
   <tag></tag>
   <elementGuidId>a93fe66c-8696-4bc1-b8dc-a583ffd44035</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ec5317ee-46be-4b07-a149-bbb89925748c']/div/div[3]/button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-check.wl-btn-icon-left</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;OK &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4a7c8894-f3cc-41d0-8b2c-3c974538295a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-check wl-btn-icon-left</value>
      <webElementGuid>bc782a99-ad25-46fd-9394-a2d58a65384f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ec5317ee-46be-4b07-a149-bbb89925748c&quot;)/div[@class=&quot;wl-msgbox-modal-content&quot;]/div[@class=&quot;wl-div-margintop10 wl-flex-center&quot;]/button[@class=&quot;wl-btn wl-btn-blue wl-marginright10 wl-flex-right wl-txt-cntr&quot;]/i[@class=&quot;fas fa-check wl-btn-icon-left&quot;]</value>
      <webElementGuid>ec7424a6-9d9a-4409-aeb3-b3d7ed5a2a4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ec5317ee-46be-4b07-a149-bbb89925748c']/div/div[3]/button/i</value>
      <webElementGuid>c3f101ab-dd77-4538-ac1e-8487e3aee005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/i</value>
      <webElementGuid>6e65a82c-0a59-4a08-9167-20aafd8ee7cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='MainContent_ucEditRoster_btnAddStaffOK']/i</value>
      <webElementGuid>83257075-8a49-4899-bf70-2c025a2e5603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[4]/button[2]/i</value>
      <webElementGuid>88b5ad00-3db3-4867-8bac-cb944d246262</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
