<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Time_ctl00MainContentucEditRosterctl0_891b56</name>
   <tag></tag>
   <elementGuidId>3b775226-08e2-4dd1-9460-34db7aad0484</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnStaff_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnStaff_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;(Select Staff)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f75a2fc-b263-4d18-84c9-2ad90ac088c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>059ca7b4-a967-4943-958a-b1a8065f023e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>(Select Staff)</value>
      <webElementGuid>c9e0b2fe-0532-4928-9da9-2171a3a05f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>(Select Staff)</value>
      <webElementGuid>6f816ec8-60e4-40af-ac12-4ea48d8b5911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$ucEditRoster$ctl01$ucRosterStrip$btnStaff</value>
      <webElementGuid>0e0b3204-b13e-452e-abc0-b912c40d8064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnStaff_0</value>
      <webElementGuid>067bcd6b-b1a7-4ef6-8d0d-3b3ed82de017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>si</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a209c50e-ce4f-4708-b0de-6e14d404d330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wl-btn-rosterstrip wl-overflow-hidden wl-width100pcnt-30 wl-display-inlineblock</value>
      <webElementGuid>e429a701-fb65-4d2a-a937-97115d211afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnStaff_0&quot;)</value>
      <webElementGuid>9bcc31ca-21ca-4d00-8795-536d8e183cd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnStaff_0']</value>
      <webElementGuid>7609edc4-ff34-47c2-a672-f006b4efc105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RosterStrip_0']/div/div/input</value>
      <webElementGuid>bba84362-228c-4d08-987c-639aa70c2bed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/input</value>
      <webElementGuid>b60741b3-3b72-4e28-b8a4-98df96aaff22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @title = '(Select Staff)' and @name = 'ctl00$MainContent$ucEditRoster$ctl01$ucRosterStrip$btnStaff' and @id = 'btnStaff_0']</value>
      <webElementGuid>50e60202-cae6-4a82-ac18-f063e6c022e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
